name: CustomKitPlugin
version: 3.4
main: de.CypDasHuhn.Kit.KitPluginMain
api-version: '1.20'

commands:
  kit:
    aliases: k
  kitPlugin:
    aliases: [kp]
  ckpTest:
    description: test class, does mostly nothing.